{
  "stats": {
    "suites": 7,
    "tests": 25,
    "passes": 15,
    "pending": 0,
    "failures": 10,
    "start": "2021-04-08T22:23:12.624Z",
    "end": "2021-04-08T22:23:12.862Z",
    "duration": 238
  },
  "tests": [
    {
      "title": "has an text input field",
      "fullTitle": "RestaurantInput has an text input field",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "RestaurantInput has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the component state with an onChange event",
      "fullTitle": "RestaurantInput changes the component state with an onChange event",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "RestaurantInput updates the state of the store after submitting the form",
      "duration": 32,
      "currentRetry": 0,
      "err": {
        "message": "expected undefined to equal 'Hello'",
        "showDiff": true,
        "expected": "Hello",
        "stack": "AssertionError: expected undefined to equal 'Hello'\n    at Context.<anonymous> (test/restaurants-test.js:44:53)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "displays a list of restaurant components",
      "fullTitle": "Restaurants Component displays a list of restaurant components",
      "duration": 8,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the appropriate text",
      "fullTitle": "Restaurant Component displays the appropriate text",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "renders an li",
      "fullTitle": "Restaurant Component renders an li",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an unique id property for each element",
      "fullTitle": "RestaurantInput Component with Redux has an unique id property for each element",
      "duration": 9,
      "currentRetry": 0,
      "err": {
        "message": "expected undefined to equal 'Sbarro'",
        "showDiff": true,
        "expected": "Sbarro",
        "stack": "AssertionError: expected undefined to equal 'Sbarro'\n    at Context.<anonymous> (test/restaurants-test.js:91:53)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "has the restaurant as a prop",
      "fullTitle": "Restaurant Component with Redux has the restaurant as a prop",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "fullTitle": "Restaurant Component with Redux has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "message": "expected 1 to equal 0",
        "showDiff": true,
        "actual": "1",
        "expected": "0",
        "stack": "AssertionError: expected 1 to equal 0\n    at Context.<anonymous> (test/restaurants-test.js:127:52)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Restaurant Component with Redux updates the state of the store to remove the component",
      "duration": 10,
      "currentRetry": 0,
      "err": {
        "message": "expected 2 to equal 1",
        "showDiff": true,
        "actual": "2",
        "expected": "1",
        "stack": "AssertionError: expected 2 to equal 1\n    at Context.<anonymous> (test/restaurants-test.js:153:52)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "displays the ReviewInput component as a child of each Restaurant Component",
      "fullTitle": "ReviewInput Component displays the ReviewInput component as a child of each Restaurant Component",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has two text input fields, one for review input, and another for submitting",
      "fullTitle": "ReviewInput Component has two text input fields, one for review input, and another for submitting",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "ReviewInput Component has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the component state with an onChange event",
      "fullTitle": "ReviewInput Component changes the component state with an onChange event",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "adds a review to the store when the form is submitted",
      "fullTitle": "ReviewInput Component adds a review to the store when the form is submitted",
      "duration": 20,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:55:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "ReviewInput Component updates the state of the store after submitting the form",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:72:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "sets a property of restaurantId on the review input component from the parent components id",
      "fullTitle": "ReviewInput Component sets a property of restaurantId on the review input component from the parent components id",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "associates the review with the restaurant with a foreign key on the review",
      "fullTitle": "ReviewInput Component associates the review with the restaurant with a foreign key on the review",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:98:16)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "is a child of the ReviewsContainer component",
      "fullTitle": "Reviews Component is a child of the ReviewsContainer component",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a review for when it is associated with the restaurant",
      "fullTitle": "Reviews Component displays a review for when it is associated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "does not display any review unassociated with the restaurant",
      "fullTitle": "Reviews Component does not display any review unassociated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an unique id property that for each element",
      "fullTitle": "Reviews Component has an unique id property that for each element",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:148:16)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "has a button that dispatches a DELETE_REVIEW action when clicked",
      "fullTitle": "Reviews Component has a button that dispatches a DELETE_REVIEW action when clicked",
      "duration": 6,
      "currentRetry": 0,
      "err": {
        "message": "expected 1 to equal 0",
        "showDiff": true,
        "actual": "1",
        "expected": "0",
        "stack": "AssertionError: expected 1 to equal 0\n    at Context.<anonymous> (test/reviews-test.js:171:44)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Reviews Component updates the state of the store to remove the component",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:185:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    }
  ],
  "pending": [],
  "failures": [
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "RestaurantInput updates the state of the store after submitting the form",
      "duration": 32,
      "currentRetry": 0,
      "err": {
        "message": "expected undefined to equal 'Hello'",
        "showDiff": true,
        "expected": "Hello",
        "stack": "AssertionError: expected undefined to equal 'Hello'\n    at Context.<anonymous> (test/restaurants-test.js:44:53)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "has an unique id property for each element",
      "fullTitle": "RestaurantInput Component with Redux has an unique id property for each element",
      "duration": 9,
      "currentRetry": 0,
      "err": {
        "message": "expected undefined to equal 'Sbarro'",
        "showDiff": true,
        "expected": "Sbarro",
        "stack": "AssertionError: expected undefined to equal 'Sbarro'\n    at Context.<anonymous> (test/restaurants-test.js:91:53)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "fullTitle": "Restaurant Component with Redux has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "message": "expected 1 to equal 0",
        "showDiff": true,
        "actual": "1",
        "expected": "0",
        "stack": "AssertionError: expected 1 to equal 0\n    at Context.<anonymous> (test/restaurants-test.js:127:52)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Restaurant Component with Redux updates the state of the store to remove the component",
      "duration": 10,
      "currentRetry": 0,
      "err": {
        "message": "expected 2 to equal 1",
        "showDiff": true,
        "actual": "2",
        "expected": "1",
        "stack": "AssertionError: expected 2 to equal 1\n    at Context.<anonymous> (test/restaurants-test.js:153:52)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "adds a review to the store when the form is submitted",
      "fullTitle": "ReviewInput Component adds a review to the store when the form is submitted",
      "duration": 20,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:55:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "ReviewInput Component updates the state of the store after submitting the form",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:72:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "associates the review with the restaurant with a foreign key on the review",
      "fullTitle": "ReviewInput Component associates the review with the restaurant with a foreign key on the review",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:98:16)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "has an unique id property that for each element",
      "fullTitle": "Reviews Component has an unique id property that for each element",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:148:16)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "has a button that dispatches a DELETE_REVIEW action when clicked",
      "fullTitle": "Reviews Component has a button that dispatches a DELETE_REVIEW action when clicked",
      "duration": 6,
      "currentRetry": 0,
      "err": {
        "message": "expected 1 to equal 0",
        "showDiff": true,
        "actual": "1",
        "expected": "0",
        "stack": "AssertionError: expected 1 to equal 0\n    at Context.<anonymous> (test/reviews-test.js:171:44)\n    at processImmediate (node:internal/timers:463:21)"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Reviews Component updates the state of the store to remove the component",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:143:19)\n    at Object.invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)\n    at Object.invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:201:43)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:461:19)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:483:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:581:5)\n    at executeDispatchesAndReleaseSimulated (node_modules/react-dom/cjs/react-dom.development.js:589:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:562:8)\n    at Object.runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:721:5)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:22\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:16660:12)\n    at /Users/sydney/Desktop/Flatiron/code/crud-lab/node_modules/react-dom/cjs/react-dom-test-utils.development.js:998:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:252:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:868:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1534:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)\n    at Context.<anonymous> (test/reviews-test.js:185:10)\n    at processImmediate (node:internal/timers:463:21)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    }
  ],
  "passes": [
    {
      "title": "has an text input field",
      "fullTitle": "RestaurantInput has an text input field",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "RestaurantInput has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the component state with an onChange event",
      "fullTitle": "RestaurantInput changes the component state with an onChange event",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a list of restaurant components",
      "fullTitle": "Restaurants Component displays a list of restaurant components",
      "duration": 8,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the appropriate text",
      "fullTitle": "Restaurant Component displays the appropriate text",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "renders an li",
      "fullTitle": "Restaurant Component renders an li",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has the restaurant as a prop",
      "fullTitle": "Restaurant Component with Redux has the restaurant as a prop",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the ReviewInput component as a child of each Restaurant Component",
      "fullTitle": "ReviewInput Component displays the ReviewInput component as a child of each Restaurant Component",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has two text input fields, one for review input, and another for submitting",
      "fullTitle": "ReviewInput Component has two text input fields, one for review input, and another for submitting",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "ReviewInput Component has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the component state with an onChange event",
      "fullTitle": "ReviewInput Component changes the component state with an onChange event",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "sets a property of restaurantId on the review input component from the parent components id",
      "fullTitle": "ReviewInput Component sets a property of restaurantId on the review input component from the parent components id",
      "duration": 3,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "is a child of the ReviewsContainer component",
      "fullTitle": "Reviews Component is a child of the ReviewsContainer component",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a review for when it is associated with the restaurant",
      "fullTitle": "Reviews Component displays a review for when it is associated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "does not display any review unassociated with the restaurant",
      "fullTitle": "Reviews Component does not display any review unassociated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {}
    }
  ]
}